name: Build and Publissh Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    permissions:
      id-token: write 
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Pack
        run: |
          cd templates
          dotnet pack --configuration release /p:Version=${{ github.event.release.tag_name }} --output ../artifacts
      - uses: actions/upload-artifact@v4
        name: Upload Package
        with:
          name: package
          path: artifacts/*.nupkg
          #     - name: NuGet push
#        run: dotnet nuget push artifacts/my-sdk.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json